{% set versions = {
    "HEAD": "latest",
    "v9.08.26": "b13f3bb4d4c9ac2ebd6c805ab9f153ea9a317d32"
} %}

{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

{% set libtorch = libtorch if libtorch else "0" %}
{% set root = root if root else "0" %}

build:
  number: 0
  string: "torch{{ libtorch.replace('.', '') }}_root{{ root.replace('.', '') }}"
  ignore_run_exports_from:
    - tbb
    - tbb-devel

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "escalade")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("-", ".") }}

source:
  git_url: "https://gitlab.cern.ch/escalade/framework.git"
  git_rev: {{ version }}

requirements:
  build:
    - root {{ root }}.*
    - cmake
    - make

  host:
    - root {{ root }}.*
    # - root-plus * torch{{ libtorch.replace('.', '') }}_root{{ root.replace('.', '') }}
    - mpi
    - hdf5

  run:
    - root {{ root }}.*
    # - root-plus * torch{{ libtorch.replace('.', '') }}_root{{ root.replace('.', '') }}
    - gettext
    - bc
    - coreutils
    - mpi
    - hdf5

about:
  home: "https://gitlab.cern.ch/escalade/framework"
  license: "GPL-3.0"
  summary: "Escalade Framework: File Processing Middleware on HPC computers"
  description: |
    Escalade is a middleware for processing large-scale file-based data, ensuring outputs for each file efficiently. It handles up to petabytes of data in a reasonable timeframe.

extra:
  recipe-maintainers:
    - meiyasan
